#!/bin/bash


VERSION="1.0"

BASE="/var/www/html/l-panel"

LOG="/var/log/l-panel-update.log"


while true
do


clear


echo "=============================="
echo "       L-PANEL MANAGER"
echo "=============================="

echo ""
echo "1) Install OCServ 1.5.0"
echo "2) Update L-PANEL from Github"
echo "3) Show Last Update"
echo "4) Remove L-PANEL Completely"
echo "5) Exit"

echo ""
read -p "Select: " option



case $option in


1)

echo "Installing OCServ 1.5.0"

bash $BASE/scripts/install-ocserv.sh

read -p "Press Enter"

;;



2)

echo "Updating..."

cd $BASE || exit


OLD=$(git rev-parse HEAD)



git fetch


NEW=$(git rev-parse origin/main)



if [ "$OLD" = "$NEW" ]

then

echo "Already latest version"

else


TOTAL=$(git diff --name-only $OLD $NEW | wc -l)


echo "Files changed: $TOTAL"


git pull


echo "$(date '+%Y-%m-%d %H:%M:%S') Updated $TOTAL files" >> $LOG


echo ""
echo "Update completed"

fi


read -p "Press Enter"

;;



3)


echo "Last Updates:"
echo ""

cat $LOG 2>/dev/null || echo "No update found"


read -p "Press Enter"

;;



4)


echo "WARNING"
echo "This removes L-PANEL"


read -p "Continue? y/n : " confirm


if [ "$confirm" == "y" ]

then


bash /var/www/html/l-panel/uninstall.sh


fi


read -p "Press Enter"

;;



5)

exit

;;


*)

echo "Invalid"

sleep 2

;;


esac


done
