#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

source "$SCRIPT_DIR/lib/colors.sh"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/commands/menu.sh"

while true
do
    show_menu

    read -rp "Select option: " OPTION

    case "$OPTION" in

        1)
            bash "$SCRIPT_DIR/commands/install.sh"
        ;;

        2)
            bash "$SCRIPT_DIR/commands/ocserv.sh"
        ;;

        3)
            bash "$SCRIPT_DIR/commands/update.sh"
        ;;

        4)
            bash "$SCRIPT_DIR/commands/uninstall.sh"
        ;;

        0)
            exit 0
        ;;

        *)
            echo "Invalid option."
            sleep 1
        ;;

    esac

done
