version: "3.8"


services:



  app:


    build:

      context: ./php

      dockerfile: Dockerfile



    container_name: lpanel_app



    working_dir: /var/www/html



    volumes:

      - ../:/var/www/html



    networks:

      - lpanel



    depends_on:

      - mysql





  nginx:


    image: nginx:latest



    container_name: lpanel_nginx



    ports:

      - "80:80"



    volumes:

      - ../:/var/www/html

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf



    depends_on:

      - app



    networks:

      - lpanel






  mysql:


    image: mariadb:10.11



    container_name: lpanel_mysql



    restart: always



    environment:


      MYSQL_DATABASE: lpanel


      MYSQL_ROOT_PASSWORD: root


    volumes:


      - mysql_data:/var/lib/mysql



    ports:


      - "3306:3306"



    networks:


      - lpanel





networks:


  lpanel:



volumes:


  mysql_data:
