CREATE TABLE IF NOT EXISTS admin_permissions (

id INT AUTO_INCREMENT PRIMARY KEY,

admin_id INT NOT NULL,

permission VARCHAR(100) NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(admin_id)
REFERENCES admins(id)
ON DELETE CASCADE

);
