CREATE TABLE IF NOT EXISTS traffic_logs (

    id INT AUTO_INCREMENT PRIMARY KEY,

    user_id INT NULL,

    download_mb BIGINT DEFAULT 0,

    upload_mb BIGINT DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
