ALTER TABLE users
ADD COLUMN IF NOT EXISTS download_gb DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS upload_gb DECIMAL(10,2) DEFAULT 0;


ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP NULL;
