CREATE TABLE admins (

id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

username VARCHAR(100) NOT NULL UNIQUE,

password VARCHAR(255) NOT NULL,

email VARCHAR(150),

role VARCHAR(50) DEFAULT 'superadmin',

status TINYINT DEFAULT 1,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP

);
