# ==========================================================
# LAK PANEL - OCSERV CONFIG
# Compatible with ocserv 1.5
# ==========================================================


# Authentication
auth = "plain[passwd=/etc/ocserv/ocpasswd]"
debug = true

# Ports
tcp-port = 443
udp-port = 443


# Runtime
run-as-user = nobody
run-as-group = daemon

socket-file = /run/ocserv.socket


# Certificate
server-cert = /etc/ssl/certs/ssl-cert-snakeoil.pem
server-key = /etc/ssl/private/ssl-cert-snakeoil.key


# Security
isolate-workers = false


# Limits
max-clients = 512
max-same-clients = 1


# Keepalive
keepalive = 300
dpd = 60
mobile-dpd = 300


# Authentication timeout
auth-timeout = 240


# Session timeout
idle-timeout = 1200
mobile-idle-timeout = 1800


# TLS
tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0:-ARCFOUR-128"


# Compression
compression = true
no-compress-limit = 256


# IP Pool
device = vpns

predictable-ips = true

ipv4-network = 192.168.100.0
ipv4-netmask = 255.255.255.0


# DNS
dns = 8.8.8.8
dns = 1.1.1.1


# Routes
route = 10.0.0.0/8
route = 172.16.0.0/12
route = 192.168.0.0/16


# Client compatibility
cisco-client-compat = true


# DTLS
dtls-legacy = true


# Logging
server-stats-reset-time = 604800


# occtl
use-occtl = true


# Default domain
default-domain = lak-panel


# Ban protection
max-ban-score = 80
ban-reset-time = 300


# Cookie
cookie-timeout = 300


# Rekey
rekey-time = 172800
rekey-method = ssl


# Do not allow roaming disabled
deny-roaming = false
