#!/bin/bash

while true
do
clear

echo "========================="
echo "      L-PANEL CLI"
echo "========================="
echo
echo "1) Update Panel"
echo "0) Exit"
echo
read -p "Select: " CHOICE

case $CHOICE in

1)

cd /opt/l-panel || exit

echo
echo "Updating..."

git pull

if [ -f composer.json ]; then
    composer install --no-dev --optimize-autoloader
fi

echo
echo "Update Completed."

read -p "Press Enter..."

;;

0)

exit

;;

*)

echo "Invalid Option"

sleep 2

;;

esac

done
